### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tp323** [tp323/SI_F1_F2#2]
- [x] d) create
- [x] d) update
- [x] d) delete
- [x] e) procedimento total alarmes (passar para função)
- [x] f) sem optimistic locking
- [x] f) com optimistic locking 
- [x] g) ?
- [x] h) sem procedimento
- [x] h) com procedimento
- [x] i) vista alarmes
- [x] j) procedimento insert vista
- [x] k) procedimento apagar registos inválidos superiores a 15 dias
- [x] l) ?
